#! /bin/sh
echo "Starting MetaXmlCreator"

CP=TheMatrixB.jar
CP=$CP:lib/Dexter.jar
CP=$CP:lib/Lexter.jar
CP=$CP:lib/Neverlang.jar
CP=$CP:lib/commons-io-2.4.jar
CP=$CP:lib/jopt-simple-4.3.jar
CP=$CP:lib/junit-4.11.jar
CP=$CP:lib/mysql-connector-java-5.1.18.jar
CP=$CP:lib/ojdbc6-11.1.0.7.0.jar
CP=$CP:lib/sqljdbc4.jar
CP=$CP:lib/super-csv-2.1.0.jar
CP=$CP:lib/json-simple-1.1.1.jar

java -Xms128m -Xmx1024m -XX:MaxPermSize=256m -classpath $CP it.cnr.isti.thematrix.tools.MetaXmlCreator $1
