#!/bin/bash
# --dry-run 


VM_PAR="-Xms128m -Xmx1024m -XX:MaxPermSize=256m"
CP_PAR=TheMatrixB.jar
CP_PAR=$CP_PAR:lib/Dexter.jar
CP_PAR=$CP_PAR:lib/Lexter.jar
CP_PAR=$CP_PAR:lib/Neverlang.jar
CP_PAR=$CP_PAR:lib/ojdbc6-11.1.0.7.0.jar
CP_PAR=$CP_PAR:lib/mysql-connector-java-5.1.18.jar
CP_PAR=$CP_PAR:lib/sqljdbc4.jar
CP_PAR=$CP_PAR:lib/commons-io-2.4.jar
CP_PAR=$CP_PAR:lib/jopt-simple-4.5.jar
CP_PAR=$CP_PAR:lib/json-simple-1.1.1.jar
CP_PAR=$CP_PAR:lib/junit-4.11.jar
CP_PAR=$CP_PAR:lib/super-csv-2.1.0.jar


java $VM_PAR -classpath $CP_PAR it.cnr.isti.thematrix.scripting.sys.TheMatrixSys --ignoreDBconnection --scriptPath scripts $@
